### ISSUE TITLE
Could not find an Biome CLI release when using `latest`

### ISSUE THREAD

**Issue by lmammino** [biomejs/setup-biome#267]
Hello,

I have recently started to see the following issue in my CI:

```plain
Could not find an Biome CLI release for linux (x64) for the given version (latest).
```

This happens with the following step in my workflow:

```yaml
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
```

If I replace `latest` with my current version (`1.9.4`), everything works as expected
